### ISSUE TITLE
Update all clients to use Cloudlink 4

### ISSUE THREAD

**Issue by MikeDev101** [meower-media-co/Legacy-Meower#3]

**Comment by CST1229** [comment]
what if, instead of patching the clients to use cl4, we patch the cloudlink extension to convert cl3 packets into cl4 packets the server understands (and back)?

**Comment by MikeDev101** [comment]
> what if, instead of patching the clients to use cl4, we patch the cloudlink extension to convert cl3 packets into cl4 packets the server understands (and back)?

That could work as well

**Comment by showierdata9978** [comment]
thats what im planning to do with MeowerBot.py before i upgrade it

**Comment by williamhorning** [comment]
This'd be a huge undertaking unless we were to go the route CST suggested, which we could probably do, though the CL extension is a bit of a mess

**Comment by MikeDev101** [comment]
> This'd be a huge undertaking unless we were to go the route CST suggested, which we could probably do, though the CL extension is a bit of a mess

Some clients (like the 3.x builds IIRC) require special attention since they do not have proper authentication support ("Enter a username here" or "Login with Scratch"). Modding the CL extension presents it's challenges, but it's the matter of handling specific build quirks where things get tricky.

**Comment by tnix100** [comment]
> > This'd be a huge undertaking unless we were to go the route CST suggested, which we could probably do, though the CL extension is a bit of a mess
> 
> Some clients (like the 3.x builds IIRC) require special attention since they do not have proper authentication support ("Enter a username here" or "Login with Scratch"). Modding the CL extension presents it's challenges, but it's the matter of handling specific build quirks where things get tricky.

Also how a few commands and data objects changed between beta 4 versions and beta 4 to beta 5.

I think some stuff has even changed during beta 5, older beta 5 and late beta 4 clients still work but have some issues like not being able to load home and having to manually set your theme to get beta 4 to work.

**Comment by williamhorning** [comment]
Also, when doing this, we should make sure all modified clients are noted with a -patched suffix so people know they won't work on the original server version

**Comment by Bloctans** [comment]
why are we even updating them? beta <5/4.8 clients are borked

**Comment by MikeDev101** [comment]
Going to give up on this project, not enough resources to commit to a already dead codebase.
