### ISSUE TITLE
Fix patched-7.13.2021.sb3 build

### ISSUE THREAD

**Issue by PizzaPizza72** [meower-media-co/Legacy-Meower#4]
I noticed the patched-7.13.2021.sb3 build gives me an error when I try to load it

**Comment by williamhorning** [comment]
Hey there, what's the error you're getting trying to load it?

**Comment by PizzaPizza72** [comment]
To williamhorning: "Oops! We couldn't connect to Meower."

**Comment by MikeDev101** [comment]
Could you provide a screenshot of the error and a copy of the WebSocket message log in your browser's inspection console (ofc censor the IP command)?

**Comment by PizzaPizza72** [comment]
> **MikeDEV wrote:**
Could you provide a screenshot of the error and a copy of the WebSocket message log in your browser's inspection console (ofc censor the IP command)?

I don't know what the IP command is, so I didn't screenshot it for my own safety.

Screenshot of the error:

<img width="476" alt="Screen Shot 2023-01-26 at 2 49 44 PM" src="https://user-images.githubusercontent.com/122486895/214936695-5214361b-990d-464b-8fed-f76e452bce0e.png">

**Comment by MikeDev101** [comment]
We need to have a copy of the network log within the browser. That error screen is generic, and will not be able to help us diagnose the issue.

**Comment by PizzaPizza72** [comment]
> We need to have a copy of the network log within the browser. That error screen is generic, and will not be able to help us diagnose the issue.

Can you please describe what the websocket message log looks like?

**Comment by tnix100** [comment]
> > We need to have a copy of the network log within the browser. That error screen is generic, and will not be able to help us diagnose the issue.
> 
> Can you please describe what the websocket message log looks like?

Go into your browser's developer tools (try f12 or CTRL+SHIFT+J or right click and choose "Inspect"), then go into "Console" and it should show the CL logs.

**Comment by PizzaPizza72** [comment]
> **MikeDEV wrote:**
We need to have a copy of the network log within the browser. That error screen is generic, and will not be able to help us diagnose the issue.
Would this help? 
<img width="1532" alt="Screen Shot 2023-01-26 at 5 05 18 PM" src="https://user-images.githubusercontent.com/122486895/214961242-6bf213e7-ab65-4931-b3e4-2128cefefd23.png">

**Comment by PizzaPizza72** [comment]
Welp, it looks like this syntax error might be causing the problem
![Uploading Screen Shot 2023-01-26 at 5.07.14 PM.png…]()

**Comment by tnix100** [comment]
> Welp, it looks like this syntax error might be causing the problem
> <img width="407" alt="Screen Shot 2023-01-26 at 5 07 14 PM" src="https://user-images.githubusercontent.com/122486895/214961578-f295b400-c9e8-421a-97bf-491c8f9b52d7.png">
> 
> 

Could you show us the sent packets?

(Except for the one that has `cmd: ip` in it)

**Comment by PizzaPizza72** [comment]
> > Welp, it looks like this syntax error might be causing the problem
> > <img alt="Screen Shot 2023-01-26 at 5 07 14 PM" width="407" src="https://user-images.githubusercontent.com/122486895/214961578-f295b400-c9e8-421a-97bf-491c8f9b52d7.png">
> 
> Could you show us the sent packets?
> 
> (Except for the one that has `cmd: ip` in it)

Sorry if I'm making you angry, but I have the file [here](https://file.io/okKaF2dFyAyj). I'm letting you diagnose it since I don't know.

**Comment by silvxrcat** [comment]
> > > Welp, it looks like this syntax error might be causing the problem
> > > <img alt="Screen Shot 2023-01-26 at 5 07 14 PM" width="407" src="https://user-images.githubusercontent.com/122486895/214961578-f295b400-c9e8-421a-97bf-491c8f9b52d7.png">
> > 
> > 
> > Could you show us the sent packets?
> > (Except for the one that has `cmd: ip` in it)
> 
> Sorry if I'm making you angry, but I have the file [here](https://file.io/okKaF2dFyAyj). I'm letting you diagnose it since I don't know.

the file is deleted

**Comment by PizzaPizza72** [comment]
> > > > Welp, it looks like this syntax error might be causing the problem
> > > > <img alt="Screen Shot 2023-01-26 at 5 07 14 PM" width="407" src="https://user-images.githubusercontent.com/122486895/214961578-f295b400-c9e8-421a-97bf-491c8f9b52d7.png">
> > > 
> > > 
> > > Could you show us the sent packets?
> > > (Except for the one that has `cmd: ip` in it)
> > 
> > 
> > Sorry if I'm making you angry, but I have the file [here](https://file.io/okKaF2dFyAyj). I'm letting you diagnose it since I don't know.
> 
> the file is deleted

I think tnix or mikedev downloaded it

**Comment by tnix100** [comment]
> 

I downloaded it, I haven't checked it out yet

**Comment by tnix100** [comment]
What CL extension are you using?

**Comment by PizzaPizza72** [comment]
> What CL extension are you using?

The regular one. (From extensions.turbowarp.org)

I've tried using Cloudlink Turbo but it throws up the same error

**Comment by tnix100** [comment]
> > What CL extension are you using?
> 
> The regular one. (From extensions.turbowarp.org)
> 
> I've tried using Cloudlink Turbo but it throws up the same error

That appears to be CL4, which is incompatible with the Meower's current CL server because we still use CL3.

**Comment by PizzaPizza72** [comment]
> > > What CL extension are you using?
> > 
> > 
> > The regular one. (From extensions.turbowarp.org)
> > I've tried using Cloudlink Turbo but it throws up the same error
> 
> That appears to be CL4, which is incompatible with the Meower's current CL server because we still use CL3.

Is there a way to get the CL3 turbowarp extension or was it deleted

**Comment by MikeDev101** [comment]
Try this: https://github.com/meower-media-co/Meower-Vanilla/blob/main/B3-0.js

**Comment by PizzaPizza72** [comment]
> **MikeDEV wrote:**
Try this: https://github.com/meower-media-co/Meower-Vanilla/blob/main/B3-0.js Edit: Actually use this one: https://github.com/MikeDev101/mikedev101.github.io/blob/master/turbo_networking.js

<img width="1677" alt="Screen Shot 2023-02-01 at 11 22 30 AM" src="https://user-images.githubusercontent.com/122486895/216101837-3a182611-5268-4b6f-8d46-a6f614a850d0.png">


<img width="496" alt="Screen Shot 2023-02-01 at 11 23 03 AM" src="https://user-images.githubusercontent.com/122486895/216101865-3e16371f-8b29-4eed-94e5-0a0b8caf079e.png">

**Comment by MikeDev101** [comment]
You don't use the GitHub raw link. You download the JS files and import them using a extension. RTM.

**Comment by PizzaPizza72** [comment]
> You don't use the GitHub raw link. You download the JS files and import them using a extension. *RTFM: [meower-media-co/Meower-Vanilla#155](https://github.com/orgs/meower-media-co/discussions/155)

I don't have javascript installed on my computer, does that matter?

**Comment by MikeDev101** [comment]
> 



> You don't use the GitHub raw link. You download the JS files and import them using a extension. *RTFM: [meower-media-co/Meower-Vanilla#155](https://github.com/orgs/meower-media-co/discussions/155)
> 
> I don't have javascript installed on my computer, does that matter?
> 
> (And by that, I mean I don't have the _programming language_ installed, not the _web Javascript_.)

*facepalm*

1. View the files from the links I sent you. Use the "RAW" button. 
![clickme](https://user-images.githubusercontent.com/12957745/216155662-6f3651b1-c3d8-403e-8d1b-038f6350252f.png)
2. CTRL+A and CTRL+C the contents of one of the files.
3. Follow the instructions, steps 4-6.

**Comment by williamhorning** [comment]
This actually isn't an issue with the patched build. RTFM
